# Site settings
title: Alumni GDM
email: lodemuyl@student.arteveldehs.be
description: > # this means to ignore newlines until "baseurl:"
 Het promoboek is een laatstejaarsproject waar we met 10 studenten uit de verschillende afstudeerrichtingen aan werken.
  Het is een soort van jaarboek, waar alle afstuderende studenten grafische en digitale media in voorkomen. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.gdm.gent/alumnigdm" # the base hostname & protocol for your site
github_username:  lodemuyl

# Build settings
markdown: kramdown
